household_consumption <- read.table("./household_power_consumption.txt",sep = ";", na.strings ="?",stringsAsFactors = FALSE,skip = 1)
n <- household_consumption$V1 == "1/2/2007" | household_consumption$V1 == "2/2/2007"
temp <- subset(household_consumption,n)
temp$V10 <- strptime(paste(temp$V1,temp$V2),format = "%d/%m/%Y %H:%M:%S")
png(filename = "Plot 4.png")
par(mfrow = c(2,2))
plot(temp$V10,temp$V3,'l',ylab = "Global Active Power",xlab = "")
plot(temp$V10,temp$V5,'l',ylab = "Voltage",xlab = "datetime")
plot(temp$V10,temp$V7,'l',ylab = "Energy sub metering",xlab = "")
lines(temp$V10,temp$V8 , col = "red")
lines(temp$V10, temp$V9 , col = "blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd = c(1,1,1))
plot(temp$V10,temp$V4,'l',ylab = "Global_Reactive_Power(kilowatts)",xlab = "datetime")
dev.off()